### ISSUE TITLE
MVP Tracking Issue

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/forc.pub#8]
This issue tracks the remaining work for an MVP package registry for forc.

- [x] Infrastructure deployment
- [x] Login with github
- [x] API authentication
- [ ] Publish feature
- [ ] Yank feature
- [ ] Search feature
- [ ] forc-build integration
- [ ] forc-publish plugin
- [ ] publish-sway-packages github action
